version: 0.2
env:
  parameter-store:
    SECRET_TOKEN: "MY_SECRET_TOKEN"
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - yum update -y
      - yum install yum-utils -y
      - yum-config-manager --add-repo https://cli.github.com/packages/rpm/gh-cli.repo -y
      - yum install gh -y
  build:
    commands:
      - echo Build started on `date`
      - echo Running tests
      - npm test; EXITCODE=$?
      - echo "$CODEBUILD_WEBHOOK_TRIGGER"
      - TAG=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed -r 's/^.{3}//')
      - echo $TAG
      - gh auth login --hostname github.com --with-token <<< $SECRET_TOKEN
      - |
        if [ "$EXITCODE" = "0" ]; then
          gh pr merge $TAG --admin --merge
          git init
          git remote add neworigin https://${SECRET_USERNAME}:${SECRET_TOKEN}@github.com/IBS-Skillset/master-source-build.git
          git config --global user.email $SECRET_EMAIL
          git config --global user.name $SECRET_USERNAME
          git checkout -B main
          git fetch --all
          git reset --hard neworigin/main
          printf "\nmy-stays-ui" >> commitList.txt
          git add commitList.txt
          git commit -m "Adding my-stays-ui PR to commitlist ${CODEBUILD_WEBHOOK_TRIGGER}"
          git push neworigin main
        else
          gh pr comment $TAG --body "The tests have failed. Please check the logs and fix the issues."
        fi
