export default {
    SEARCH_LOCATION: 'Search a Location',
    NO_AVAILABLE_HOTELS: 'No available hotels matching your request were found. Please amend your search criteria.',
    INTERNAL_SERVER: 'Internal server error',
    EXPERIENCING_ISSUES: 'Currently Experiencing some issues! Please try again later',
    NO_AVAILABILITY: 'No Availability',
    BOOKING_FAILED: 'Your booking has failed. Please try again.',
    INCORRECT_DATE_RANGE: 'Incorrect Date Range',
    BOOKING_SUCCESS: 'Your trip has been successfully booked. Thank you for your reservation.',
    LOCATION_REQUIRED: '*Location is required',
    CVC_REQUIRED: 'CVC is required',
    CVC_LEAST: 'CVC must be at least 3 characters',
    CVC_MOST: 'CVC must be at most 4 characters',
    INVALID_CVC: 'Invalid CVC',
    CARD_NUMBER_REQUIRED: 'Card number is required',
    TEST_NUMBER: 'test-number',
    INVALID_CARD_NUMBER: 'Invalid card number',
    EXPIRY_DATE_REQUIRED: 'Expiry date is required',
    INVALID_EXPIRY_DATE: 'Invalid expiry date',
    CARDHOLDER_NAME_REQUIRED: 'Card holder name is required',
    INVALID_EMAIL: 'Invalid email',
    EMAIL_REQUIRED:'*Email is required',
    ENTER_FIRSTNAME: 'Please enter first name',
    FIRSTNAME_REQUIRED: '*Firstname is required',
    TOO_LONG: 'Too Long!',
    ENTER_LASTNAME: 'Please enter last name',
    LASTNAME_REQUIRED: '*Lastname is required',
    PASSWORD_REQUIRED: '*Password is required',
    PHONE_NUMBER_REQUIRED: 'Phone number is required',
    PHONE_NUMBER_12_DIGITS: 'Phone number must be 12 digits with country code',
    COMPLETED: 'You have currently no completed trips!',
    UPCOMING: 'You have currently no upcoming trips!',
    LOGGED_OUT: 'You will be logged out automatically in 1 minute',
    USER_IDLE: 'user is idle',
    LAST_ACTIVE: 'last active',
    USER_ACTIVE: 'user is active',
    TIME_REMAINING: 'time remaining',
    DID_SOMETHING: 'user did something',
    GEOLOCATION_ERROR: 'An error occurred while calling GeoLocation Places',
    USER_NOT_FOUND: 'user not found',
    ROOM_AVAIL_RESPONSE: 'Room Availability Response'
}