---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-stays-ui
  namespace: beta-app
  labels:
    app.kubernetes.io/name: my-stays-ui
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: my-stays-ui
  template:
    metadata:
      labels:
        app.kubernetes.io/name: my-stays-ui
    spec:
      containers:
        - name: my-stays-ui-api
          image: 306472407007.dkr.ecr.ap-south-1.amazonaws.com/ibs-skillset-happystays/my-stays-ui:01ea16e
          imagePullPolicy: Always
          env:
            - name: HOST_UI
              value: my-stays-ui
          ports:
            - name: web
              containerPort: 80
          resources:
            requests:
              memory: "250Mi"
              cpu: "200m"
            limits:
              memory: "500Mi"
